-- drop database if exists stockManagement;
-- create database if not exists stockManagement;

drop table if exists PRODUCT;

drop table if exists SUPPLIER;

create table if not exists SUPPLIER(ID int auto_increment,
NAME varchar(255) not null,
DATE_OF_CREATION date not null,
DATE_LAST_UPDATE date,
PRIMARY KEY (ID),
CONSTRAINT UC_SNAME UNIQUE (NAME));

create table if not exists PRODUCT(ID int auto_increment,
NAME varchar(255) not null,
QUANTINTY numeric(18, 2) not null,
UNIT_PRICE numeric(18, 2) not null,
SUPPLIER_ID int not null,
DATE_OF_CREATION date not null,
DATE_LAST_UPDATE date,
PRIMARY KEY (ID),
CONSTRAINT UK_PSUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID));

-- Supplier records
INSERT INTO SUPPLIER(ID, NAME, DATE_OF_CREATION) VALUES(1, 'AGRO PRODUÇÕES E INVESTIMENTOS', (SELECT SYSDATE()));
INSERT INTO SUPPLIER(ID, NAME, DATE_OF_CREATION) VALUES(2, 'INDÚSTRIA DE PRODUTOS ALIMENTARES - RIO DE JANEIRO', (SELECT SYSDATE()));
INSERT INTO SUPPLIER(ID, NAME, DATE_OF_CREATION) VALUES(3, 'FÁBRICA DE BOLACHAS - LUZ VERDE', (SELECT SYSDATE()));

-- Product Records
INSERT INTO PRODUCT(ID, NAME, QUANTINTY, UNIT_PRICE, SUPPLIER_ID, DATE_OF_CREATION) VALUES(1, 'TOMATE', 100.00, 5.00, (SELECT ID FROM SUPPLIER WHERE NAME = 'AGRO PRODUÇÕES E INVESTIMENTOS'), (SELECT SYSDATE()));
INSERT INTO PRODUCT(ID, NAME, QUANTINTY, UNIT_PRICE, SUPPLIER_ID, DATE_OF_CREATION) VALUES(2, 'PIMENTO', 150.00, 3.00, (SELECT ID FROM SUPPLIER WHERE NAME = 'INDÚSTRIA DE PRODUTOS ALIMENTARES - RIO DE JANEIRO'), (SELECT SYSDATE()));
INSERT INTO PRODUCT(ID, NAME, QUANTINTY, UNIT_PRICE, SUPPLIER_ID, DATE_OF_CREATION) VALUES(3, 'LARANJA', 150.00, 3.00, (SELECT ID FROM SUPPLIER WHERE NAME = 'INDÚSTRIA DE PRODUTOS ALIMENTARES - RIO DE JANEIRO'), (SELECT SYSDATE()));

