-- drop database if exists cayena_pmgm;
-- create database if not exists cayena_pmgm;

drop table if exists PRODUCT;

drop table if exists SUPPLIER;

create table if not exists SUPPLIER(ID int auto_increment,
NAME varchar(500) not null,
DATE_OF_CREATION date not null,
DATE_OF_LAST_UPDATE date,
PRIMARY KEY (ID),
CONSTRAINT UC_SUPPLIER_NAME UNIQUE (NAME));

create table if not exists PRODUCT(ID int auto_increment,
NAME varchar(255) not null,
QUANTINTY numeric(18, 2) not null,
UNIT_PRICE numeric(18, 2) not null,
SUPPLIER_ID int not null,
DATE_OF_CREATION date not null,
DATE_OF_LAST_UPDATE date,
PRIMARY KEY (ID),
CONSTRAINT UK_PRODUCT_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID),
CONSTRAINT UC_PRODUCT_SUPPLIER UNIQUE (NAME, SUPPLIER_ID, DATE_OF_CREATION));

-- Supplier records
INSERT INTO SUPPLIER(ID, NAME, DATE_OF_CREATION) VALUES(1, 'AGRO PRODUÇÕES E INVESTIMENTOS', TO_DATE('20/10/2021', 'DD/MM/YYYY'));
INSERT INTO SUPPLIER(ID, NAME, DATE_OF_CREATION) VALUES(2, 'INDÚSTRIA DE PRODUTOS ALIMENTARES - RIO DE JANEIRO', TO_DATE('18/10/2021', 'DD/MM/YYYY'));
INSERT INTO SUPPLIER(ID, NAME, DATE_OF_CREATION) VALUES(3, 'FÁBRICA DE BOLACHAS - LUZ VERDE', TO_DATE('17/10/2021', 'DD/MM/YYYY'));

-- Product Records
INSERT INTO PRODUCT(ID, NAME, QUANTINTY, UNIT_PRICE, SUPPLIER_ID, DATE_OF_CREATION) VALUES(1, 'TOMATE', 100.00, 5.00, (SELECT ID FROM SUPPLIER WHERE NAME = 'AGRO PRODUÇÕES E INVESTIMENTOS'), TO_DATE('20/10/2021', 'DD/MM/YYYY'));
INSERT INTO PRODUCT(ID, NAME, QUANTINTY, UNIT_PRICE, SUPPLIER_ID, DATE_OF_CREATION) VALUES(2, 'PIMENTO', 150.00, 3.00, (SELECT ID FROM SUPPLIER WHERE NAME = 'INDÚSTRIA DE PRODUTOS ALIMENTARES - RIO DE JANEIRO'), TO_DATE('20/10/2021', 'DD/MM/YYYY'));

